#!/usr/bin/env ruby

require 'rack'
require 'optparse'
require 'codeme/manager/version'
require 'codeme/manager/server'
require 'codeme/manager'

options = {
  Port: ENV['PORT'] || 3000,
  Host: "0.0.0.0",
  AccessLog: []
}

OptionParser.new do |opts|
  opts.on("-v", "--version", "Display Codeme::Manager version") {
    puts "Codeme::Manager #{Codeme::Manager::VERSION}"
    exit
  }

  opts.on("-h", "--help") {
    puts opts
    exit
  }

  opts.separator ""
  opts.on("-s", "--server SERVER", "Run Codeme::Manager server") { |name| handlers.unshift(name.to_s) }
  opts.on("-o", "--host HOST", "The listen on HOST (default: 0.0.0.0)") { |host| options[:Host] = host.to_s; puts host }
  opts.on("-p", "--port PORT", "The listen on PORT (default: 3000)") { |port| options[:Port] = port.to_i }
  opts.on("-C", "--config FILE", "The external configuration file") { |config| require File.join(Dir.pwd, config) }

  opts.parse! ARGV
end

begin
  config = Codeme::Manager::Config
  case config.auth_type
  when :token
    raise LoadError.new("Token authorization require to set token") if config.token.nil?
  end

  Rack::Handler.default.run Codeme::Manager::Server, options
rescue LoadError => e
  # TODO: Improve error message
  STDERR.puts e
end
